version: 2

sources:
  - name: clickhouse
    database: {{ var('src_clickhouse_schema', 'default') }}
    tables:
      - name: {{ var('src_clickhouse_table', 'default_table') }}
        +enabled: "{{ target.name == 'dev' }}"

  - name: ds_internal
    database: {{ var('src_internal_schema', 'default') }}
    tables:
      - name: {{ var('src_internal_table', 'default_table') }}
        +enabled: "{{ target.name == 'dev' }}"