dbt_mi:
  outputs:
    dev:
      type: clickhouse
      host: "{{ env_var('CLICKHOUSE_HOST') }}"
      port: 8123
      #port: "{{ env_var('CLICKHOUSE_PORT', '8123') }}"
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      #database: "{{ env_var('CLICKHOUSE_DB', 'default') }}"
      #secure: true
      schema: ds_internal

  target: dev

mi_profile:
    outputs:
      dev:
       type: sqlserver
       host: "{{ env_var('SQLSERVER_HOST') }}"
       port: "{{ env_var('SQLSERVER_PORT', '1433') }}"
       user: "{{ env_var('SQLSERVER_USER') }}"
       password: "{{ env_var('SQLSERVER_PASSWORD') }}"
       database: "{{ env_var('SQLSERVER_DB', 'master') }}"
       schema: "{{ env_var('SQLSERVER_SCHEMA', 'dbo') }}"
       secure: true
       driver: "ODBC Driver 18 for SQL Server"
       encrypt: Yes
       trust_cert: Yes

    target: dev
